### ISSUE TITLE
Number should not be stored as a string

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-ui#169]
![image](https://user-images.githubusercontent.com/18637436/190549634-9ac430aa-01e2-4958-9c7a-d03e797a8e4d.png)

**Comment by oanhhynguyen** [comment]
if user has as blank then its null
![image](https://user-images.githubusercontent.com/88865245/190563921-c4d55557-89ad-42d9-a1dd-0be80ad2635a.png)
