### ISSUE TITLE
plugins install

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-ui#362]
https://github.com/NubeIO/rubix-ui/blob/fc1760c3a9c45972fe995f641d2b81f877c097dd/frontend/src/components/hosts/host/flow/plugins/factory.tsx#L67

**Comment by RaiBnod** [comment]
Here are the functions:

- For listing distributions:

  https://github.com/NubeIO/rubix-ui/blob/3957f435216578b1c644c2a66774b6d659ba9d68/frontend/src/components/hosts/host/flow/plugins/factory.tsx#L21-L23

- For doing installation/uninstallation:

  https://github.com/NubeIO/rubix-ui/blob/3957f435216578b1c644c2a66774b6d659ba9d68/frontend/src/components/hosts/host/flow/plugins/factory.tsx#L50-L56
