### ISSUE TITLE
Bulk Add Points

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-ui#367]
Give the user a way to bulk add points
![image](https://user-images.githubusercontent.com/18637436/203208470-f12d42a2-4949-4110-83a0-8d012a7d733c.png)

**Comment by nguyenoanh5597** [comment]
hi @NubeDev, 
when creating a new point, the name cannot be duplicated, 
so I suggest: when user enter `name` , we need to add a count after the name like: `name_1`
how do you think?
