### ISSUE TITLE
how does user set the device type

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-ui#457]
https://github.com/NubeIO/releases/blob/master/flow/v0.9.20.json#L83

the device is type rubix-compute-io

![image](https://user-images.githubusercontent.com/18637436/210018650-91185b6c-392e-45a5-a58d-8702f4c7e148.png)

**Comment by RaiBnod** [comment]
This will be device type updater: https://github.com/NubeIO/rubix-ui/issues/409
