### ISSUE TITLE
flow networks new apis

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-ui#513]
please give the apis needed for the updates to the flow-networks, eg resync and things like this

**Comment by RaiBnod** [comment]
Parent tickets:
- https://github.com/NubeIO/flow-framework/pull/508
- https://github.com/NubeIO/flow-framework/pull/785

Need to have a `Sync` button on each page and call respective APIs. Which will updates the status on the current records:

### FlowNetwork side:

#### Sync> flow_network
- `GET: /api/flow_networks/sync?with_streams=true&with_producers=true&with_writer_clones=true`

#### Sync> flow_network's streams
- `GET: /api/flow_networks/<fn_uuid>/sync/streams?with_producers=true&with_writer_clones=true`

#### Sync> stream's producers
- `GET: /api/streams/<stream_uuid>/sync/producers?with_writer_clones=true`

#### Sync> producer's writer_clones
- `GET: /api/producers/<producer_uuid>/sync/writer_clones`

### FlowNetworkClone side:

#### Sync> flow_network_clone
- `GET: /api/flow_network_clones/sync?with_stream_clones=true&with_consumers=true&with_writers=true`

#### Sync> flow_network_clone's stream_clones
- `GET: /api/flow_network_clones/<fnc_uuid>/sync/stream_clones?with_consumers=true&with_writers=true`

#### Sync> stream_clone's consumers
- `GET:  /api/stream_clones/<stream_clone_uuid>/sync/consumers?with_writers=true`

#### Sync> consumer's writers
- `GET: /api/consumers/<consumer_uuid>/sync/writers`
