### ISSUE TITLE
Deleted input link should be the same as never having a link connected

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-ui#558]
When a node is first created n.ReadPin(name) == nil. However when a link is connected, then deleted, then n.ReadPin(name) == 0.

This should not be the case. When a link is deleted, the node input should be the same as if it had never had a link connected (ie. n.ReadPin(name) == nil).

This issue seems to be coming from the UI. This is the relevant part of the JSON sent by rubix-ui the backend (This is sent when the PID node is first added, with no inputs connected, and no overrides manually set):
```
 "nodes": [
        {
            "id": "E3006E42A6F0427AB87272FC582BE130",
            "type": "hvac/pid",
            "metadata": {
                "positionX": "122.12760330182721",
                "positionY": "116.38886083675146",
                "dynamicInputs": false,
                "dynamicOutputs": false
            },
            "inputs": {
                "bias": {},
                "direction": {
                    "value": false
                },
                "enable": {
                    "value": false
                },
```

You can see that the direction and enable (all boolean values), have their values set to false initially.

**Comment by CanuckMarc** [comment]
Moded to `rubix-ui` issue

**Comment by CanuckMarc** [comment]
@JiaFei1991

**Comment by CanuckMarc** [comment]
@minhhau99 This issue is similar to the other one that you just finished.  

In this video you can see that once the link with value `111` is connected, the value of the right node is now `111` (Correct).  But when the link is deleted the output of the right node doesn't go back to `null`, even though both inputs are `null`. 


https://user-images.githubusercontent.com/40550860/220820626-367b5f31-280f-48f8-8a26-3f479d913997.mp4

**Comment by minhhau99** [comment]
@CanuckMarc 
please check for me it is exactly what you want

**Comment by CanuckMarc** [comment]
I can't see any branch or PR linked to this issue yet.

**Comment by minhhau99** [comment]
@CanuckMarc I fixed it in PR before and it merged into master, and now it's working like this

https://user-images.githubusercontent.com/120352098/222031693-e79cb5f0-7e9a-462d-8d79-68f005940dae.mov

**Comment by CanuckMarc** [comment]
@minhhau99 oh, I gottcha now.  Ya that is exactly the functionality I wanted to see.  Thanks!
