### ISSUE TITLE
send times as UTC0 for event and exception

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-ui#584]
https://momentjs.com/
https://github.com/NubeIO/flow-framework/wiki/Schedule
![image](https://user-images.githubusercontent.com/18637436/214942496-85e8390a-7bf4-479b-83ca-399e958b9737.png)

**Comment by CanuckMarc** [comment]
@JiaFei1991 

Let me know if you want any help with this.  I've done most of the schedule setup so far, and timezones are always complicated.  

Make sure you're using the Timezone versions of MomentJS: https://momentjs.com/timezone/

Also, you can find descriptions of the ScheduleJSON properties on this wiki page: https://github.com/NubeIO/flow-framework/wiki/Schedule

**Comment by CanuckMarc** [comment]
**TIMEZONES:**
- Add dropdown to select Timezone to Schedule Settings.
- Add timezone display to the `Create Schedules` UI popup.
- Get rid of Seconds selection in the timeselect options.
- User only sees timestamps in Local Time. 

**SCHEDULE NAMES**
- Schedule Settings need a add/edit field to create available `Schedule Names`. Also to set a default `Schedule Name`.
- When creating a new scheduled period (Weekly, Event, Exception), the user needs to be able to select from the list of Schedule Names that were configured in the previous settings.
