### ISSUE TITLE
wizard for remote flow connection

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/rubix-ui#643]
![image](https://user-images.githubusercontent.com/18637436/217087318-6f47a7b4-4252-4b73-8718-9ef5ee51dd3e.png)

1. step one @RaiBnod to confirm
2. add remote ip and let user ping to test it
3. fetch local token
4. fetch remote token

**Comment by RaiBnod** [comment]
@riteshakya037 
![image](https://user-images.githubusercontent.com/6800775/218098757-c552b76e-8ef5-4458-abcb-a1446afd77d2.png)
